apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  namespace: pihole
  creationTimestamp: null
  labels:
    app: pihole-nfs-client
  name: pihole-nfs-client
parameters:
  archiveOnDelete: "true"
  pathPattern:  "${.PVC.namespace}/${.PVC.name}/${.PVC.annotations.nfs.io/storage-path}"
provisioner: cluster.local/nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate

