apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: pihole
  namespace: pihole
  labels:
    app.kubernetes.io/instance: pihole
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pihole
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
